"""intentos de contrasena: 5 fallos bloquean 10 minutos

Revision ID: 25bc10d5296e
Revises: 0044
Create Date: 2026-10-01 09:21:37.505977

"""
import sqlalchemy as sa

from alembic import op

revision = '25bc10d5296e'
down_revision = '0044'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('intentos_login',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('clave', sa.String(length=180), nullable=False),
    sa.Column('intentos', sa.Integer(), nullable=False),
    sa.Column('bloqueado_hasta', sa.DateTime(timezone=True), nullable=True),
    sa.Column('actualizado_en', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_intentos_login_clave'), 'intentos_login', ['clave'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_intentos_login_clave'), table_name='intentos_login')
    op.drop_table('intentos_login')
    # ### end Alembic commands ###
