"""limites de uso: freno en lo que cuesta dinero

Revision ID: 9255aeb6c29a
Revises: 25bc10d5296e
Create Date: 2026-10-01 09:55:56.622584

"""
import sqlalchemy as sa

from alembic import op

revision = '9255aeb6c29a'
down_revision = '25bc10d5296e'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('limites_uso',
    sa.Column('clave', sa.String(length=180), nullable=False),
    sa.Column('ventana_inicio', sa.DateTime(timezone=True), nullable=False),
    sa.Column('usos', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('clave')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('limites_uso')
    # ### end Alembic commands ###
